version: '3.3'

services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./meshui-app
    volumes:
      - /usr/src/app/node_modules
      - ./meshui-app:/usr/src/app
    ports:
      - 3000:3000
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./meshui-api
    volumes:
      - /usr/src/app/node_modules
      - ./meshui-api:/usr/src/app
    ports:
      - 3001:3000
  